# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------
[[main]]
  identifier = "/"
  parent = ""
  pre = "ğŸ "
  post = ""
  name = "é¦–é¡µ"
  url = "/"
  title = ""
  weight = 1
  [main.params]
  #  icon = "fa-solid fa-home"
[[main]]
  identifier = "archives"
  parent = ""
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  name = "å½’æ¡£"
  url = "/archives/"
  # title will be shown when you hover on this menu link
  title = ""
  weight = 2
  # FixIt 0.2.14 | NEW add user-defined content to menu items
  [main.params]
    # add css class to a specific menu item
    class = ""
    # whether set as a draft menu item whose function is similar to a draft post/page
    draft = false
    # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
    icon = "fa-solid fa-archive"
    # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
    type = ""
[[main]]
  identifier = "categories"
  parent = ""
  pre = ""
  post = ""
  name = "åˆ†ç±»"
  url = "/categories/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "tags"
  parent = ""
  pre = ""
  post = ""
  name = "æ ‡ç­¾"
  url = "/tags/"
  title = ""
  weight = 4
  [main.params]
    icon = "fa-solid fa-tags"
[[main]]
  identifier = "projects"
  parent = ""
  pre = ""
  post = ""
  name = "ä½œå“"
  url = "/projects/"
  title = ""
  weight = 5
  [main.params]
    icon = "fa-solid fa-laptop-code"
[[main]]
  identifier = "diy"
  pre = ""
  post = ""
  name = "å®éªŒå®¤"
  url = "/diy/"
  title = ""
  weight = 6
  [main.params]
    icon = "fa-solid fa-flask"
[[main]]
  identifier = "navigate"
  parent = "diy"
  pre = ""
  post = ""
  name = "å¯¼èˆª"
  url = "https://xdev.cc/"
  title = ""
  weight = 1
  [main.params]
    icon = "fa-solid fa-compass"
[[main]]
  identifier = "home"
  pre = "ğŸ"
  post = ""
  name = "æ¨å¹¿"
  url = "/home/"
  title = ""
  weight = 8
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "å…³äº"
  url = "/about/"
  title = ""
  weight = 9
  [main.params]
    icon = "fa-solid fa-user-tie"
