# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
posts = "posts/:year:month/:slugorcontentbasename"
private = ":sections[1:]/:slugorcontentbasename"
