# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/configuration/privacy/
# -------------------------------------------------------------------------------------

[googleAnalytics]
  disable = false
  respectDoNotTrack = true

[instagram]
  disable = false
  simple = false

[x]
  disable = false
  enableDNT = false
  simple = false

[youtube]
  disable = false
  privacyEnhanced = false